name: AutoPkg Run via Python

on:
  # schedule:
  #   - cron: "0 0 * * *"  # Adjust schedule as needed
  workflow_dispatch:  # Enables manual triggering
  push:
    branches:
      - git-example

jobs:
  autopkg-run:
    runs-on: macos-latest
    env:
      MUNKI_VERSION: 6.6.5
      MUNKI_EXPLICIT_VERSION: 6.6.5.4711
      APKG_VERSION: 2.7.6 # 'AUTOPKG_' gets injected as an env var
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for accurate diffs

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            metadata_cache.json
          key: cache-${{ hashFiles('uv.lock') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install AutoPkg
        uses: joncrain/macos-pkg-install@v1.0
        with:
          pkg_url: https://github.com/autopkg/autopkg/releases/download/v${{ env.APKG_VERSION }}/autopkg-${{ env.APKG_VERSION }}.pkg

      - name: Install Munki
        uses: joncrain/macos-pkg-install@v1.0
        with:
          pkg_url: https://github.com/munki/munki/releases/download/v${{ env.MUNKI_VERSION }}/munkitools-${{ env.MUNKI_EXPLICIT_VERSION }}.pkg

      - name: Configure AutoPkg
        run: |
          AUTOPKG_DIR="${GITHUB_WORKSPACE}/AutoPkg"
          MUNKI_DIR="${GITHUB_WORKSPACE}/Munki"

          defaults write com.github.autopkg CACHE_DIR "${AUTOPKG_DIR}/Cache"
          defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool TRUE
          defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
          defaults write com.github.autopkg MUNKI_REPO "${MUNKI_DIR}"
          defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "${AUTOPKG_DIR}/Overrides"
          defaults write com.github.autopkg RECIPE_REPO_DIR "${AUTOPKG_DIR}/RecipeRepos"

          mkdir -p "${MUNKI_DIR}/pkgs"

      - name: AutoPkg Repo Add
        run: |
          defaults read com.github.autopkg
          cat "AutoPkg/repo_list.txt" | xargs autopkg repo-add
          defaults read com.github.autopkg

      - name: Run AutoPkg
        run: |
          defaults read com.github.autopkg
          uv run examples/git_worktree_example.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autopkg-run-artifacts
          path: |
            AutoPkg/Cache/**/*receipt*
            AutoPkg/Reports/*
            autopkg_runner.log
            metadata_cache.json
