name: AutoPkg Run via Python

on:
  # schedule:
  #   - cron: "0 0 * * *"  # Adjust schedule as needed
  workflow_dispatch:  # Enables manual triggering
  push:
    branches:
      - git-example

jobs:
  autopkg-run:
    runs-on: macos-latest
    env:
      MUNKI_VERSION: 6.7.0
      MUNKI_EXPLICIT_VERSION: 6.7.0.4731
      APKG_VERSION: 2.7.6 # 'AUTOPKG_' gets injected as an env var
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for accurate diffs

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            metadata_cache.json
          key: cache-${{ hashFiles('uv.lock') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install AutoPkg
        uses: joncrain/macos-pkg-install@v1.0
        with:
          pkg_url: https://github.com/autopkg/autopkg/releases/download/v${{ env.APKG_VERSION }}/autopkg-${{ env.APKG_VERSION }}.pkg

      - name: Install Munki
        uses: joncrain/macos-pkg-install@v1.0
        with:
          pkg_url: https://github.com/munki/munki/releases/download/v${{ env.MUNKI_VERSION }}/munkitools-${{ env.MUNKI_EXPLICIT_VERSION }}.pkg

      - name: Configure AutoPkg
        run: |
          AUTOPKG_DIR="${GITHUB_WORKSPACE}/AutoPkg"
          MUNKI_DIR="${GITHUB_WORKSPACE}/Munki"

          defaults write com.github.autopkg CACHE_DIR "${AUTOPKG_DIR}/Cache"
          defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool TRUE
          defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
          defaults write com.github.autopkg MUNKI_REPO "${MUNKI_DIR}"
          defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "${AUTOPKG_DIR}/Overrides"
          defaults write com.github.autopkg RECIPE_REPO_DIR "${AUTOPKG_DIR}/RecipeRepos"

          mkdir -p "${MUNKI_DIR}/pkgs"

      - name: AutoPkg Repo Add
        run: |
          cat "AutoPkg/repo_list.txt" | xargs autopkg repo-add
          defaults read com.github.autopkg > /dev/null 2>&1

      - name: Diagnose Git Ignore Rules
        run: |
          echo "--- Checking ignore status for Munki/icons/1Password.png ---"
          git check-ignore -v Munki/icons/1Password.png || echo "Not explicitly ignored in local .gitignore or any known global/system ignores for this path."

          echo ""
          echo "--- Checking ignore status for Munki/pkgsinfo/apps/passwordmanagers/1Password-8.11.8.plist ---"
          git check-ignore -v Munki/pkgsinfo/apps/passwordmanagers/1Password-8.11.8.plist || echo "Not explicitly ignored in local .gitignore or any known global/system ignores for this path."

          echo ""
          echo "--- Listing global gitignore if present ---"
          GLOBAL_GITIGNORE=$(git config --get core.excludesfile)
          if [ -n "$GLOBAL_GITIGNORE" ]; then
            echo "Global gitignore found at: $GLOBAL_GITIGNORE"
            if [ -f "$GLOBAL_GITIGNORE" ]; then
              cat "$GLOBAL_GITIGNORE"
            else
              echo "Global gitignore file '$GLOBAL_GITIGNORE' does not exist."
            fi
          else
            echo "No global gitignore file configured."
          fi

          echo ""
          echo "--- Current working directory for context ---"
          pwd

          echo ""
          echo "--- Listing files in Munki/icons and Munki/pkgsinfo for context ---"
          ls -F Munki/icons/
          ls -F Munki/pkgsinfo/
          ls -F Munki/pkgsinfo/apps/

      - name: Run AutoPkg
        run: |
          uv run examples/git_worktree_example.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autopkg-run-artifacts
          path: |
            AutoPkg/Cache/**/*receipt*
            AutoPkg/Reports/*
            autopkg_runner.log
            metadata_cache.json
            Munki
