name: Scheduled AutoPkg Workflow

on:
  schedule:
    - cron: "0 0 * * *"  # Adjust schedule as needed
  workflow_dispatch:  # Enables manual triggering

jobs:
  autopkg-run:
    runs-on: macos-latest
    env:
      MUNKI_VERSION: 6.6.5
      MUNKI_EXPLICIT_VERSION: 6.6.5.4711
      AUTOPKG_VERSION: 2.7.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for accurate diffs

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            /tmp/autopkg_metadata.json
            .venv
          key: cache-${{ hashFiles('uv.lock') }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install AutoPkg
        uses: joncrain/macos-pkg-install@v1
        with:
          pkg_url: https://github.com/autopkg/autopkg/releases/download/v${{ env.AUTOPKG_VERSION }}/autopkg-${{ env.AUTOPKG_VERSION }}.pkg

      - name: Install Munki
        uses: joncrain/macos-pkg-install@v1
        with:
          pkg_url: https://github.com/munki/munki/releases/download/v${{ env.MUNKI_VERSION }}/munkitools-${{ env.MUNKI_EXPLICIT_VERSION }}.pkg

      - name: Configure AutoPkg
        run: |
          AUTOPKG_DIR="${{ github.workspace }}/AutoPkg"
          MUNKI_DIR="${{ github.workspace }}/Munki"

          defaults write com.github.autopkg CACHE_DIR "${AUTOPKG_DIR}/Cache"
          defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool TRUE
          defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
          defaults write com.github.autopkg MUNKI_REPO "${MUNKI_DIR}"
          defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "${AUTOPKG_DIR}/Overrides"
          # defaults write com.github.autopkg RECIPE_REPO_DIR "${AUTOPKG_DIR}/RecipeRepos"
          defaults write com.github.autopkg RECIPE_SEARCH_DIRS -array-add "${AUTOPKG_DIR}/Recipes"

          mkdir "${MUNKI_DIR}/pkgs"

      - name: Setup Metadata Files
        run: |
          if [[ ! -f /tmp/autopkg_metadata.json ]]; then
              echo "autopkg_metadata.json not found. Creating an empty file."
              echo "{}" > /tmp/autopkg_metadata.json
          fi

          echo "Copying autopkg_metadata.json to original_autopkg_metadata.json to detect changes."
          cp /tmp/autopkg_metadata.json original_autopkg_metadata.json

      - name: AutoPkg Repo Add
        run: |
          cat "${{ github.workspace }}/AutoPkg/repo_list.txt" | xargs autopkg repo-add

      - name: Determine Recipe List
        id: recipe_list
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD AutoPkg/Overrides/*.recipe)

          if [[ ! -z "${CHANGED_FILES}" ]]; then
            TEMP_RECIPE_LIST=$(mktemp)
            RECIPE_LIST=$(echo "${CHANGED_FILES}" | grep 'AutoPkg/Overrides/.*\.recipe' | sed 's/AutoPkg\/Overrides\///g' | jq -R -s 'split("\n")[:-1]')
            echo "${RECIPE_LIST}" > "${TEMP_RECIPE_LIST}"

            echo "RECIPE_LIST=${TEMP_RECIPE_LIST}" >> $GITHUB_OUTPUT
          else
            echo "RECIPE_LIST=AutoPkg/recipe_list.json" >> $GITHUB_OUTPUT
          fi

      - name: Run AutoPkg
        run: |
          uv run autopkg-run --recipe-list "${{ steps.recipe_list.outputs.RECIPE_LIST }}"

      # - name: Combine Reports
      #   run: |
      #     combined_plist="autopkg-combined-receipts-$(date -u +%Y%m%d-%H%M%S).plist"

      #     # Create a new plist file or clear the existing one
      #     /usr/libexec/PlistBuddy -c 'Clear dict' "${combined_plist}"

      #     # Find all plist files matching *receipt*.plist in the cache directory
      #     cache_dir="$(defaults read com.github.autopkg CACHE_DIR)"
      #     plist_files=($(find "${cache_dir}" -type f -regex ".*-receipt-[0-9]\{8\}-[0-9]\{6\}\.plist$"))

      #     for plist in "${plist_files[@]}"; do
      #       local plist_name=$(basename "${plist}" .plist)
      #       echo "Adding ${plist} to combined receipts."

      #       # Add a new dictionary for this receipt under its name
      #       /usr/libexec/PlistBuddy -c "Add :${plist_name} array" "${combined_plist}"

      #       # Merge the receipt data directly under the plist name
      #       /usr/libexec/PlistBuddy -x -c "Merge ${plist} :${plist_name}" "${combined_plist}"
      #     done

      #     echo "Combined plist saved to ${combined_plist}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: autopkg-artifacts-staging
          path: |
            autopkg-combined-receipts-*.plist
            autopkg_runner.log
            metadata_cache.json
            original_autopkg_metadata.json
